Repository rustwasm/wasm-pack, pull requests merged in 2018-05, with the labels that each got.

#120 feat(error_msg): Make custom module for errors
  src/bindgen.rs
  src/build.rs
  src/command.rs
  src/error.rs
  src/lib.rs
  src/manifest.rs
  src/npm.rs
  src/progressbar.rs
  src/readme.rs
Labels: needs review

#100 Wrap npm adduser
  src/command.rs
  src/npm.rs
Labels: changes requested

#134 Logging
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  src/command.rs
  src/lib.rs
  src/logger.rs
  src/main.rs
  tests/fixtures/bad-cargo-toml/Cargo.lock
  tests/fixtures/bad-cargo-toml/Cargo.toml
  tests/fixtures/js-hello-world/Cargo.lock
  tests/fixtures/js-hello-world/Cargo.toml
  tests/fixtures/no-compile/Cargo.lock
  tests/fixtures/no-compile/Cargo.toml
  tests/fixtures/no-readme/Cargo.lock
  tests/fixtures/no-readme/Cargo.toml
  tests/fixtures/scopes/Cargo.lock
  tests/fixtures/scopes/Cargo.toml
Labels: changes requested, needs docs
