Repository rustwasm/wasm-pack, pull requests merged in 2018-09, with the labels that each got.

#282 add support for otp when publishing to npm
  src/npm.rs
Labels: needs review

#312 modules modules modules
  src/manifest/mod.rs
  src/manifest/npm/commonjs.rs
  src/manifest/npm/esmodules.rs
  src/manifest/npm/mod.rs
  src/manifest/npm/repository.rs
  tests/all/manifest.rs
  tests/all/utils/manifest.rs
Labels: needs review

#327 support no-modules
  src/bindgen.rs
  src/manifest/mod.rs
  src/manifest/npm/mod.rs
  src/manifest/npm/nomodules.rs
  tests/all/manifest.rs
  tests/all/utils/manifest.rs
Labels: needs review

#328 Fix broken links in book by replacing absolute paths with relative paths
  docs/src/SUMMARY.md
  docs/src/commands/index.md
  docs/src/commands/init.md
  docs/src/contributing.md
  docs/src/getting-started/index.md
  docs/src/getting-started/project-setup/index.md
  docs/src/prerequisites/index.md
  docs/src/tutorial/index.md
Labels: needs review

#246 the infamous docs pr
  .travis.yml
  docs/index.html
  docs/installer/index.html
  docs/public/custom.css
  docs/public/img/rustwasm.png
  docs/public/img/wasm-ferris.png
  docs/src/SUMMARY.md
  docs/src/command/pack-and-publish.md
  docs/src/commands/build.md
  docs/src/getting-started/index.md
  docs/src/getting-started/installation.md
  docs/src/getting-started/project-setup/manual-setup.md
  docs/src/prerequisites.md
  docs/src/prerequisites/index.md
  docs/src/prerequisites/npm.md
  docs/src/prerequisites/rust.md
  docs/src/project-setup/index.md
  docs/src/project-setup/manual-setup.md
  docs/src/project-setup/using-a-template.md
  docs/src/setup.md
  docs/src/tutorial/example-output.png
  docs/src/tutorial/getting-started.md
  docs/src/tutorial/index.md
  docs/src/tutorial/packaging-and-publishing.md
  docs/src/tutorial/template-deep-dive.md
  docs/src/tutorial/template-deep-dive/cargo-toml.md
  docs/src/tutorial/template-deep-dive/index.md
  docs/src/tutorial/template-deep-dive/src-lib-rs.md
  docs/src/tutorial/template-deep-dive/src-utils-rs.md
  docs/src/tutorial/using-your-library.md
  docs/src/tutorial/writing-a-rust-webassembly-library.md
Labels: Blocking Rust 2018, Rust 2018 Release Candidate

#336 Pass `--debug` to `wasm-bindgen` in debug mode
  src/bindgen.rs
Labels: needs review

#359 Add section on IDE config files to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: waiting on response

#353 feat(build): add rustc check
  Cargo.lock
  README.md
  src/build.rs
  src/command/build.rs
  src/emoji.rs
  src/error.rs
Labels: needs review

#316 v0.5.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  demo.gif
Labels: release
