Repository rustwasm/wasm-pack, pull requests merged in 2018-12, with the labels that each got.

#411 Copy license file(s) to out directory
  Cargo.lock
  Cargo.toml
  src/command/build.rs
  src/lib.rs
  src/license.rs
  src/manifest/mod.rs
  tests/all/license.rs
  tests/all/main.rs
  tests/all/utils/fixture.rs
Labels: changes requested

#446 feat: Catch typos in Cargo.toml and warn about them
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/manifest/mod.rs
  tests/all/manifest.rs
Labels: needs review

#453 Generate self-.gitignore as part of pkg folder
  src/command/utils.rs
Labels: needs docs, waiting on response

#444 pre-build before wasm-pack publish
  Cargo.lock
  Cargo.toml
  src/command/build.rs
  src/command/mod.rs
  src/command/publish/mod.rs
  src/command/utils.rs
  src/lib.rs
  src/logger.rs
Labels: waiting on response
