Repository rustwasm/wasm-pack, pull requests merged in 2019-03, with the labels that each got.

#517 test(binaryinstall): Add initial tests
  .appveyor.yml
  .travis.yml
  binary-install/Cargo.toml
  binary-install/src/lib.rs
  binary-install/tests/all/cache.rs
  binary-install/tests/all/download.rs
  binary-install/tests/all/main.rs
  binary-install/tests/all/utils/mod.rs
Labels: changelog - maintenance

#566 Fix tests on master
  tests/all/utils/fixture.rs
Labels: changelog - fix

#565 Flag gh-pages docs as unpublished
  .travis.yml
  docs/_theme/header.hbs
Labels: changelog - docs, waiting on response

#567 Add support for `--target web`
  docs/src/commands/build.md
  src/bindgen.rs
  src/command/build.rs
  src/command/publish/mod.rs
  src/manifest/mod.rs
  tests/all/manifest.rs
Labels: changelog - feature

#569 Update prerequisites documentation
  docs/src/SUMMARY.md
  docs/src/prerequisites/index.md
  docs/src/prerequisites/rust.md
Labels: changes requested, waiting on response

#547 Migrate output towards the 1.0 strategy
  Cargo.lock
  Cargo.toml
  src/bindgen.rs
  src/build.rs
  src/child.rs
  src/command/build.rs
  src/command/login.rs
  src/command/pack.rs
  src/command/publish/mod.rs
  src/command/test.rs
  src/command/utils.rs
  src/lib.rs
  src/license.rs
  src/manifest/mod.rs
  src/progressbar.rs
  src/readme.rs
  src/test/webdriver.rs
  tests/all/license.rs
  tests/all/manifest.rs
  tests/all/readme.rs
  tests/all/test.rs
Labels: changelog - feature

#576 webpack tutorial and some docs nits
  README.md
  docs/public/custom.css
  docs/src/SUMMARY.md
  docs/src/tutorials/hybrid-applications-with-webpack/getting-started.md
  docs/src/tutorials/hybrid-applications-with-webpack/index.md
  docs/src/tutorials/hybrid-applications-with-webpack/using-your-library.md
  docs/src/tutorials/index.md
  docs/src/tutorials/npm-browser-packages/building-your-package.md
  docs/src/tutorials/npm-browser-packages/getting-started.md
  docs/src/tutorials/npm-browser-packages/index.md
  docs/src/tutorials/npm-browser-packages/packaging-and-publishing.md
  docs/src/tutorials/npm-browser-packages/project-setup/index.md
  docs/src/tutorials/npm-browser-packages/project-setup/manual-setup.md
  docs/src/tutorials/npm-browser-packages/project-setup/using-a-template.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/building-your-project.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/cargo-toml.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/index.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-lib-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-utils-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/wee_alloc.md
  docs/src/tutorials/npm-browser-packages/using-your-library.md
  docs/src/tutorials/standalone-wasm-binaries/index.md
Labels: changelog - docs, needs review

#549 0.7.0
  .travis.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/index.html
Labels: release

#590 Smorgasboard of doc improvements
  docs/src/SUMMARY.md
  docs/src/prerequisites/index.md
  docs/src/tutorials/npm-browser-packages/building-your-package.md
  docs/src/tutorials/npm-browser-packages/building-your-project.md
  docs/src/tutorials/npm-browser-packages/getting-started.md
  docs/src/tutorials/npm-browser-packages/getting-started/manual-setup.md
  docs/src/tutorials/npm-browser-packages/project-setup/index.md
  docs/src/tutorials/npm-browser-packages/project-setup/using-a-template.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/cargo-toml.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/index.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-lib-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-utils-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/tests-web-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/wee_alloc.md
  docs/src/tutorials/npm-browser-packages/testing-your-project.md
Labels: changelog - docs, changes requested

#593 doc(build): add entry for --out-dir
  docs/src/commands/build.md
Labels: changelog - docs, needs review

#598 Fix panics in `build --mode no-install`
  src/command/build.rs
  tests/all/build.rs
Labels: changelog - fix, needs review

#600 chore: Remove binary-install
  .appveyor.yml
  Cargo.lock
  Cargo.toml
  binary-install/Cargo.toml
  binary-install/README.md
  binary-install/src/lib.rs
  binary-install/tests/all/cache.rs
  binary-install/tests/all/download.rs
  binary-install/tests/all/main.rs
  binary-install/tests/all/utils/mod.rs
Labels: changelog - maintenance, needs review

#601 feat: Print unexpected panics to standard error
  src/main.rs
Labels: changelog - fix

#602 Improve error message when wasm32-unknown-unknown is missing
  docs/src/SUMMARY.md
  docs/src/non-rustup-setups.md
  docs/src/prerequisites/index.md
  src/build/mod.rs
  src/build/wasm_target.rs
  src/command/build.rs
  src/command/test.rs
Labels: changelog - fix

#599 Added support for --out-name flag
  docs/src/commands/build.md
  src/bindgen.rs
  src/command/build.rs
  src/command/test.rs
  src/manifest/mod.rs
  tests/all/license.rs
  tests/all/lockfile.rs
  tests/all/manifest.rs
Labels: changelog - feature

#610 fix(doc): put non rustup conetnt in the right spot
  docs/src/SUMMARY.md
  docs/src/prerequisites/non-rustup-setups.md
Labels: needs review
