Repository rustwasm/wasm-pack, pull requests merged in 2019-02, with the labels that each got.

#537 Use win32 chromedriver binary on win64, update chromedriver version and fix error message
  src/test/webdriver.rs
  tests/all/webdriver.rs
Labels: needs review

#542 [Docs] Add wee_alloc section
  docs/src/SUMMARY.md
  docs/src/tutorial/template-deep-dive/src-lib-rs.md
  docs/src/tutorial/template-deep-dive/wee_alloc.md
Labels: changelog - docs, needs review

#478 Refactor: fix clippy warnings
  clippy.toml
  src/child.rs
  src/command/build.rs
  src/command/login.rs
  src/command/mod.rs
  src/command/publish/mod.rs
  src/command/utils.rs
  src/installer.rs
  src/lockfile.rs
  src/manifest/mod.rs
  src/npm.rs
  src/progressbar.rs
  src/readme.rs
Labels: changelog - maintenance

#502 chore(travis): Run clippy check
  .travis.yml
Labels: changelog - maintenance

#536 rust webpack template tutorial
  docs/src/SUMMARY.md
  docs/src/tutorials/hybrid-applications-with-webpack/getting-started.md
  docs/src/tutorials/hybrid-applications-with-webpack/index.md
  docs/src/tutorials/hybrid-applications-with-webpack/template-deep-dive/building-your-project.md
  docs/src/tutorials/hybrid-applications-with-webpack/template-deep-dive/cargo-toml.md
  docs/src/tutorials/hybrid-applications-with-webpack/template-deep-dive/index.md
  docs/src/tutorials/hybrid-applications-with-webpack/template-deep-dive/src-lib-rs.md
  docs/src/tutorials/hybrid-applications-with-webpack/using-your-library.md
  docs/src/tutorials/npm-browser-packages/index.md
Labels: changelog - docs, needs review

#555 "Wasm" is a contraction, not an acronym
  src/bindgen.rs
  src/build.rs
  src/command/test.rs
Labels: changelog - docs

#550 fix(exe): wasm-pack-init (1).exe should work
  src/main.rs
Labels: changelog - fix, needs review
