Repository rustwasm/wasm-pack, pull requests merged in 2019-04, with the labels that each got.

#612 fix the docs
  .travis.yml
  docs/src/SUMMARY.md
  docs/src/introduction.md
  docs/src/prerequisites/index.md
  docs/src/prerequisites/npm.md
  docs/src/tutorials/hybrid-applications-with-webpack/index.md
  docs/src/tutorials/npm-browser-packages/getting-started/manual-setup.md
  docs/src/tutorials/npm-browser-packages/index.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/cargo-toml.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-lib-rs.md
  docs/src/tutorials/npm-browser-packages/template-deep-dive/src-utils-rs.md
Labels: changelog - docs, needs review

#614 doc: Fix broken links
  docs/src/prerequisites/index.md
  docs/src/tutorials/hybrid-applications-with-webpack/index.md
  docs/src/tutorials/npm-browser-packages/getting-started/manual-setup.md
Labels: changelog - docs

#604 0.8.0
  CHANGELOG.md
  README.md
  docs/index.html
Labels: TWiRaWA, release

#616 fix: Check for "rustup" rather than ".rustup" when checking for wasm32
  src/build/wasm_target.rs
Labels: changelog - fix

#619 0.8.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/index.html
Labels: release

#409 added wasm-pack feature which compares local and latest wasm-pack versions
  Cargo.lock
  Cargo.toml
  src/build/mod.rs
  src/command/build.rs
  src/lib.rs
  src/main.rs
  src/manifest/mod.rs
Labels: changelog - feature

#628 refactor: Use PBAR.warn and a struct for versions
  src/build/mod.rs
  src/command/build.rs
  src/main.rs
  src/manifest/mod.rs
Labels: changelog - maintenance, needs review

#626 doc(release): add release checklist
  RELEASE_CHECKLIST.md
Labels: changelog - maintenance

#630 Only run specific tests during `wasm-pack test`
  docs/src/commands/test.md
  src/command/test.rs
Labels: changelog - feature, changelog - fix, needs docs
