Repository rustwasm/wasm-pack, pull requests merged in 2019-07, with the labels that each got.

#670 Update cargo_metadata to 0.8.0
  Cargo.lock
  Cargo.toml
  src/manifest/mod.rs
Labels: changelog - maintenance

#624 Recurse up the path looking for the Cargo.toml
  src/command/build.rs
  src/command/mod.rs
  src/command/pack.rs
  src/command/publish/mod.rs
  src/command/test.rs
  src/command/utils.rs
  tests/all/build.rs
  tests/all/manifest.rs
Labels: changelog - feature, needs review

#683 test: Ensure that `wasm-bindgen` will generate move assertions
  tests/all/build.rs
Labels: changelog - maintenance

#684 check wasm-bindgen version if running with target web
  Cargo.lock
  Cargo.toml
  src/bindgen.rs
  src/child.rs
  src/install/mod.rs
  src/lib.rs
  src/manifest/mod.rs
  tests/all/build.rs
Labels: needs review

#625 Add support for automatically executing `wasm-opt`
  docs/src/cargo-toml-configuration.md
  src/child.rs
  src/command/build.rs
  src/lib.rs
  src/manifest/mod.rs
  src/wasm_opt.rs
  tests/all/main.rs
  tests/all/utils/fixture.rs
  tests/all/wasm_opt.rs
Labels: changelog - feature, needs rebase

#682 feat(bindgen): update to --target flag interface
  src/bindgen.rs
  src/command/build.rs
  tests/all/utils/fixture.rs
Labels: changelog - maintenance, needs review

#690 feat(publish): dist tag option
  docs/src/commands/pack-and-publish.md
  src/command/mod.rs
  src/command/publish/mod.rs
  src/npm.rs
Labels: changelog - feature
