Repository rustwasm/wasm-pack, pull requests merged in 2019-01, with the labels that each got.

#487 Login issues
  src/npm.rs
Labels: changelog - fix

#484 validate target argument
  src/command/build.rs
Labels: changelog - fix

#490 Complete template deep dives
  docs/src/tutorial/template-deep-dive/cargo-toml.md
  docs/src/tutorial/template-deep-dive/src-lib-rs.md
  docs/src/tutorial/template-deep-dive/src-utils-rs.md
Labels: changelog - docs

#489 Windows fixes
  src/child.rs
  src/npm.rs
Labels: changelog - fix

#488 v0.6.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release

#461 add an option to pass an arbitrary set of arguments to cargo build
  docs/src/commands/build.md
  src/build.rs
  src/command/build.rs
  tests/all/build.rs
Labels: changelog - feature

#495 get binary install ready for publish
  Cargo.lock
  Cargo.toml
  binary-install/Cargo.toml
  binary-install/README.md
  binary-install/src/lib.rs
  src/bindgen.rs
  src/command/build.rs
  src/command/test.rs
  src/lib.rs
  src/test/webdriver.rs
  tests/all/bindgen.rs
  tests/all/main.rs
  tests/all/utils/fixture.rs
  tests/all/webdriver.rs
Labels: changelog - maintenance

#498 small cleanup
  .gitignore
  CHANGELOG.md
Labels: needs review

#504 More logging and assertions
  Cargo.lock
  binary-install/Cargo.toml
  binary-install/src/lib.rs
  src/bindgen.rs
  src/command/test.rs
  src/test/webdriver.rs
  tests/all/bindgen.rs
  tests/all/utils/fixture.rs
Labels: changelog - maintenance

#514 doc: Fix links and Rust highlightning
  docs/src/prerequisites/index.md
  docs/src/tutorial/index.md
  docs/src/tutorial/template-deep-dive/src-utils-rs.md
Labels: changelog - docs

#516 doc: Use absolute url in prerequisites index
  docs/src/prerequisites/index.md
Labels: changelog - docs

#521 Only print `cargo test` output the once
  Cargo.lock
  Cargo.toml
  src/cache.rs
  src/command/build.rs
  src/command/test.rs
  src/lib.rs
  src/progressbar.rs
  src/test/mod.rs
  tests/all/main.rs
  tests/all/test.rs
  tests/all/utils/fixture.rs
Labels: changelog - fix

#527 Support license-file field in Cargo.toml
  src/license.rs
  src/manifest/mod.rs
  tests/all/license.rs
  tests/all/utils/fixture.rs
Labels: changelog - feature, needs review

#531 Support 'homepage' field of Cargo.toml and package.json
  src/manifest/mod.rs
  src/manifest/npm/commonjs.rs
  src/manifest/npm/esmodules.rs
  src/manifest/npm/nomodules.rs
  tests/all/manifest.rs
  tests/all/utils/manifest.rs
Labels: changelog - feature

#530 Pass arguments through to cargo test
  docs/src/commands/build.md
  docs/src/commands/test.md
  src/build.rs
  src/command/build.rs
  src/command/test.rs
  src/test/mod.rs
Labels: changelog - feature, needs review

#528 Add license files and README file to 'files' field of package.json
  src/command/build.rs
  src/manifest/mod.rs
  tests/all/manifest.rs
Labels: changelog - fix

#532 Add examples of running individual tests to the testing docs
  docs/src/commands/test.md
Labels: changelog - docs
